name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/latex:2.16.1
    steps:
      - uses: actions/checkout@v2
      - run: |
          tlmgr install cleveref siunitx
      - run: |
          pandoc --standalone --output=worksheet.docx README.md -F pandoc-crossref --citeproc
      - run: |
          git add worksheet.docx && git commit -m "update worksheet" && git fetch origin main && git push origin main
      - uses: actions/upload-artifact@master
        with:
          name: worksheet
          path: worksheet.docx
