name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: pandoc/latex:2.16.1
    steps:
      - uses: actions/checkout@v2
      - run: |
          tlmgr install cleveref siunitx
      - run: |
          pandoc --standalone --output=worksheet.docx README.md -F pandoc-crossref --citeproc
      - uses: actions/upload-artifact@master
        with:
          name: worksheet
          path: worksheet.docx
